package com.mycompany.mavenprojecttesti;
// Generated Feb 11, 2019 2:17:32 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Kayttaja generated by hbm2java
 */
@Entity
@Table(name="kayttaja"
    ,catalog="laiterekisteri"
)
public class Kayttaja  implements java.io.Serializable {

    @Id
   @GeneratedValue(strategy=IDENTITY)
    @Column(name = "id")
     private Integer id;
    
    @Column(name ="nimi")
     private String nimi;
    
    @Column(name ="salasana")
     private String salasana;
    
    @Column(name = "valtuudet")
     private int valtuudet;

    public Kayttaja() {
        super();
    }

    public Kayttaja(String nimi, String salasana, int valtuudet) {
        super();
       this.nimi = nimi;
       this.salasana = salasana;
       this.valtuudet = valtuudet;
    }
   
 
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    public String getNimi() {
        return this.nimi;
    }
    
    public void setNimi(String nimi) {
        this.nimi = nimi;
    }

    
    public String getSalasana() {
        return this.salasana;
    }
    
    public void setSalasana(String salasana) {
        this.salasana = salasana;
    }


    public int getValtuudet() {
        return this.valtuudet;
    }
    
    public void setValtuudet(int valtuudet) {
        this.valtuudet = valtuudet;
    }




}


