package Model;
// Generated Feb 12, 2019 2:31:28 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Kayttaja generated by hbm2java
 */
@Entity
@Table(name="kayttaja"
    ,catalog="laiterekisteri"
)
public class Kayttaja  implements java.io.Serializable {


     private Integer id;
     private String nimi;
     private String salasana;
     private int valtuudet;
     private Set<Varaukset> varauksets = new HashSet<Varaukset>(0);

    public Kayttaja() {
    }

	
    public Kayttaja(String nimi, String salasana, int valtuudet) {
        this.nimi = nimi;
        this.salasana = salasana;
        this.valtuudet = valtuudet;
    }
    public Kayttaja(String nimi, String salasana, int valtuudet, Set<Varaukset> varauksets) {
       this.nimi = nimi;
       this.salasana = salasana;
       this.valtuudet = valtuudet;
       this.varauksets = varauksets;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="Id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    
    @Column(name="Nimi", nullable=false, length=40)
    public String getNimi() {
        return this.nimi;
    }
    
    public void setNimi(String nimi) {
        this.nimi = nimi;
    }

    
    @Column(name="Salasana", nullable=false, length=40)
    public String getSalasana() {
        return this.salasana;
    }
    
    public void setSalasana(String salasana) {
        this.salasana = salasana;
    }

    
    @Column(name="Valtuudet", nullable=false)
    public int getValtuudet() {
        return this.valtuudet;
    }
    
    public void setValtuudet(int valtuudet) {
        this.valtuudet = valtuudet;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="kayttaja")
    public Set<Varaukset> getVarauksets() {
        return this.varauksets;
    }
    
    public void setVarauksets(Set<Varaukset> varauksets) {
        this.varauksets = varauksets;
    }




}


