package Model;
// Generated Feb 12, 2019 11:02:13 AM by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * ResurssitId generated by hbm2java
 */
@Embeddable
public class ResurssitId implements java.io.Serializable {

    private int id;
    private String nimi;

    public ResurssitId() {
    }

    public ResurssitId(int id, String nimi) {
        this.id = id;
        this.nimi = nimi;
    }

    @Column(name = "Id", nullable = false)
    public int getId() {
        return this.id;
    }

    public void setId(int id) {
        this.id = id;
    }

    @Column(name = "Nimi", nullable = false, length = 40)
    public String getNimi() {
        return this.nimi;
    }

    public void setNimi(String nimi) {
        this.nimi = nimi;
    }

    public boolean equals(Object other) {
        if ((this == other)) {
            return true;
        }
        if ((other == null)) {
            return false;
        }
        if (!(other instanceof ResurssitId)) {
            return false;
        }
        ResurssitId castOther = (ResurssitId) other;

        return (this.getId() == castOther.getId())
                && ((this.getNimi() == castOther.getNimi()) || (this.getNimi() != null && castOther.getNimi() != null && this.getNimi().equals(castOther.getNimi())));
    }

    public int hashCode() {
        int result = 17;

        result = 37 * result + this.getId();
        result = 37 * result + (getNimi() == null ? 0 : this.getNimi().hashCode());
        return result;
    }

}
