package Model;
// Generated Feb 12, 2019 11:02:13 AM by Hibernate Tools 4.3.1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinColumns;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Varaukset generated by hbm2java
 */
@Entity
@Table(name = "varaukset",
         catalog = "laiterekisteri"
)
public class Varaukset implements java.io.Serializable {

    private Integer varausId;
    private Kayttaja kayttaja;
    private Resurssit resurssit;
    private Date alkupvm;
    private Date paattymispvm;
    private String kuvaus;
    private boolean palautettu;
    private byte hyvaksytty;

    public Varaukset() {
    }

    public Varaukset(Kayttaja kayttaja, Resurssit resurssit, Date alkupvm, Date paattymispvm, String kuvaus, boolean palautettu) {
        this.kayttaja = kayttaja;
        this.resurssit = resurssit;
        this.alkupvm = alkupvm;
        this.paattymispvm = paattymispvm;
        this.kuvaus = kuvaus;
        this.palautettu = palautettu;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)

    @Column(name = "VarausID", unique = true, nullable = false)
    public Integer getVarausId() {
        return this.varausId;
    }

    public void setVarausId(Integer varausId) {
        this.varausId = varausId;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "Id", nullable = false)
    public Kayttaja getKayttaja() {
        return this.kayttaja;
    }

    public void setKayttaja(Kayttaja kayttaja) {
        this.kayttaja = kayttaja;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumns({
        @JoinColumn(name = "ResurssiId", referencedColumnName = "Id", nullable = false)
        , 
        @JoinColumn(name = "Nimi", referencedColumnName = "Nimi", nullable = false)})
    public Resurssit getResurssit() {
        return this.resurssit;
    }

    public void setResurssit(Resurssit resurssit) {
        this.resurssit = resurssit;
    }

    @Temporal(TemporalType.DATE)
    @Column(name = "Alkupvm", nullable = false, length = 10)
    public Date getAlkupvm() {
        return this.alkupvm;
    }

    public void setAlkupvm(Date alkupvm) {
        this.alkupvm = alkupvm;
    }

    @Temporal(TemporalType.DATE)
    @Column(name = "Paattymispvm", nullable = false, length = 10)
    public Date getPaattymispvm() {
        return this.paattymispvm;
    }

    public void setPaattymispvm(Date paattymispvm) {
        this.paattymispvm = paattymispvm;
    }

    @Column(name = "Kuvaus", nullable = false, length = 40)
    public String getKuvaus() {
        return this.kuvaus;
    }

    public void setKuvaus(String kuvaus) {
        this.kuvaus = kuvaus;
    }

    @Column(name = "Palautettu", nullable = false)
    public boolean isPalautettu() {
        return this.palautettu;
    }

    public void setPalautettu(boolean palautettu) {
        this.palautettu = palautettu;
    }

    @Column(name = "Hyvaksytty", nullable = true)
    public byte getHyvaksytty() {
        return hyvaksytty;
    }

    public void setHyvaksytty(byte hyvaksytty) {
        this.hyvaksytty = hyvaksytty;
    }

}
