package Model;
// Generated Mar 3, 2019 5:42:43 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Kayttaja generated by hbm2java
 */
@Entity
@Table(name="Kayttaja"
    ,catalog="laiterekisteri"
)
public class Kayttaja  implements java.io.Serializable {


     private Integer id;
     private String nimi;
     private String salasana;
     private String kayttajatunnus;
     private String sahkoposti;
     private int valtuudet;
     private Set<Varaukset> varauksets = new HashSet<Varaukset>(0);

    public Kayttaja() {
    }

	
    public Kayttaja(String nimi, String salasana, String kayttajatunnus, String sahkoposti, int valtuudet) {
        this.nimi = nimi;
        this.salasana = salasana;
        this.kayttajatunnus = kayttajatunnus;
        this.sahkoposti = sahkoposti;
        this.valtuudet = valtuudet;
    }
    public Kayttaja(String nimi, String salasana, String kayttajatunnus, String sahkoposti, int valtuudet, Set<Varaukset> varauksets) {
       this.nimi = nimi;
       this.salasana = salasana;
       this.kayttajatunnus = kayttajatunnus;
       this.sahkoposti = sahkoposti;
       this.valtuudet = valtuudet;
       this.varauksets = varauksets;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="Id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    
    @Column(name="Nimi", nullable=false, length=40)
    public String getNimi() {
        return this.nimi;
    }
    
    public void setNimi(String nimi) {
        this.nimi = nimi;
    }

    
    @Column(name="Salasana", nullable=false, length=40)
    public String getSalasana() {
        return this.salasana;
    }
    
    public void setSalasana(String salasana) {
        this.salasana = salasana;
    }

    
    @Column(name="Kayttajatunnus", nullable=false, length=40)
    public String getKayttajatunnus() {
        return this.kayttajatunnus;
    }
    
    public void setKayttajatunnus(String kayttajatunnus) {
        this.kayttajatunnus = kayttajatunnus;
    }

    
    @Column(name="Sahkoposti", nullable=false, length=80)
    public String getSahkoposti() {
        return this.sahkoposti;
    }
    
    public void setSahkoposti(String sahkoposti) {
        this.sahkoposti = sahkoposti;
    }

    
    @Column(name="Valtuudet", nullable=false)
    public int getValtuudet() {
        return this.valtuudet;
    }
    
    public void setValtuudet(int valtuudet) {
        this.valtuudet = valtuudet;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="kayttaja")
    public Set<Varaukset> getVarauksets() {
        return this.varauksets;
    }
    
    public void setVarauksets(Set<Varaukset> varauksets) {
        this.varauksets = varauksets;
    }




}


