package Model;
// Generated Mar 6, 2019 4:26:26 PM by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Kayttaja generated by hbm2java
 */
@Entity
@Table(name = "Kayttaja",
         catalog = "laiterekisteri"
)
public class Kayttaja implements java.io.Serializable {

    private Integer id;
    private String nimi;
    private String salasana;
    private int valtuudet;
    private String kayttajatunnus;
    private String sahkoposti;
    private Set<Varaukset> varauksets = new HashSet<Varaukset>(0);

    /**
     * Tyhjä konstruktio.
     */
    public Kayttaja() {
    }

    /**
     * Konstruktio ilman ensimmäistä varausta.
     * @param nimi
     * @param salasana
     * @param kayttajatunnus
     * @param sahkoposti
     * @param valtuudet
     */
    public Kayttaja(String nimi, String salasana, String kayttajatunnus, String sahkoposti, int valtuudet) {
        this.nimi = nimi;
        this.salasana = salasana;
        this.valtuudet = valtuudet;
        this.kayttajatunnus = kayttajatunnus;
        this.sahkoposti = sahkoposti;
    }

    /**
     * Konstruktio varauksen kanssa.
     * @param nimi
     * @param salasana
     * @param valtuudet
     * @param kayttajatunnus
     * @param sahkoposti
     * @param varauksets
     */
    public Kayttaja(String nimi, String salasana, int valtuudet, String kayttajatunnus, String sahkoposti, Set<Varaukset> varauksets) {
        this.nimi = nimi;
        this.salasana = salasana;
        this.valtuudet = valtuudet;
        this.kayttajatunnus = kayttajatunnus;
        this.sahkoposti = sahkoposti;
        this.varauksets = varauksets;
    }

    /** 
     * getteri käyttäjä id:lle
     * @return
     */
    @Id
    @GeneratedValue(strategy = IDENTITY)

    @Column(name = "Id", unique = true, nullable = false)
    public Integer getId() {
        return this.id;
    }

    /**
     * setteri käyttäjä id:lle
     * @param id
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * getteri käyttäjä nimelle
     * @return
     */
    @Column(name = "Nimi", nullable = false, length = 40)
    public String getNimi() {
        return this.nimi;
    }

    /**
     * Setteri käyttäjä nimelle
     * @param nimi
     */
    public void setNimi(String nimi) {
        this.nimi = nimi;
    }

    /**
     * getteri käyttäjä salasanalle
     * @return
     */
    @Column(name = "Salasana", nullable = false, length = 40)
    public String getSalasana() {
        return this.salasana;
    }

    /**
     *  setteri käyttäjä salasanalle
     * @param salasana
     */
    public void setSalasana(String salasana) {
        this.salasana = salasana;
    }

    /**
     * getteri käyttäjä valtuuksille
     * @return
     */
    @Column(name = "Valtuudet", nullable = false)
    public int getValtuudet() {
        return this.valtuudet;
    }

    /**
     * setteri käyttäjä valtuuksille
     * @param valtuudet
     */
    public void setValtuudet(int valtuudet) {
        this.valtuudet = valtuudet;
    }

    /**
     * getteri käyttäjä käyttäjätunnukselle
     * @return
     */
    @Column(name = "Kayttajatunnus", nullable = false, length = 40)
    public String getKayttajatunnus() {
        return this.kayttajatunnus;
    }

    /**
     * setteri käyttäjä käyttäjätunnukselle
     * @param kayttajatunnus
     */
    public void setKayttajatunnus(String kayttajatunnus) {
        this.kayttajatunnus = kayttajatunnus;
    }

    /**
     * getteri käyttäjä sähköpostille
     * @return
     */
    @Column(name = "Sahkoposti", nullable = false, length = 80)
    public String getSahkoposti() {
        return this.sahkoposti;
    }

    /**
     * setteri käyttäjä sähköpostille
     * @param sahkoposti
     */
    public void setSahkoposti(String sahkoposti) {
        this.sahkoposti = sahkoposti;
    }

    /**
     * getteri käyttäjä varauksille
     * @return
     */
    @OneToMany(fetch = FetchType.EAGER, mappedBy = "kayttaja")
    public Set<Varaukset> getVarauksets() {
        return this.varauksets;
    }

    /**
     * setteri käyttäjä varauksille
     * @param varauksets
     */
    public void setVarauksets(Set<Varaukset> varauksets) {
        this.varauksets = varauksets;
    }

}
